name: Enviar Cursos Gratuitos a Telegram

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  ejecutar-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el codigo
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install requests

      - name: Ejecutar script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python buscador_cursos.py
